[project]
name = "mlx-api"
version = "0.1.0"
description = "API server for MLX-Whisper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "mlx-whisper>=0.4.2",
]
license = "MIT"
